//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicacion
    {
        public aplicacion()
        {
            this.perfilaplicacion = new HashSet<perfilaplicacion>();
        }
    
        public int aplicacion_id { get; set; }
        public string aplicacion_nombre { get; set; }
        public string aplicacion_Descripcion { get; set; }
    
        public virtual ICollection<perfilaplicacion> perfilaplicacion { get; set; }
    }
}
