//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class emisionlimite
    {
        public emisionlimite()
        {
            this.emisionevento = new HashSet<emisionevento>();
        }
    
        public Nullable<int> emisionlimite_dias { get; set; }
        public string emisionlimite_descripcion { get; set; }
        public int emisionlimite_producto_1 { get; set; }
        public int emisionlimite_producto_2 { get; set; }
        public int emisionlimite_proceso_id { get; set; }
    
        public virtual ICollection<emisionevento> emisionevento { get; set; }
        public virtual emisionproceso emisionproceso { get; set; }
        public virtual ramo ramo { get; set; }
    }
}
