//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class emisionproceso
    {
        public emisionproceso()
        {
            this.emisionlimite = new HashSet<emisionlimite>();
        }
    
        public int emisionproceso_id { get; set; }
        public string emisionproceso_nombre { get; set; }
        public string emisionproceso_descripcion { get; set; }
    
        public virtual ICollection<emisionlimite> emisionlimite { get; set; }
    }
}
