//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class emisionevento
    {
        public int emisionevento_id { get; set; }
        public string emisionevento_poliza_numero { get; set; }
        public int emisionevento_proceso_id { get; set; }
        public int emisionevento_estado_id { get; set; }
        public int emisionevento_producto_1 { get; set; }
        public int emisionevento_producto_2 { get; set; }
        public string emisionevento_descripcion { get; set; }
        public System.DateTime emisionevento_fecha_inicio { get; set; }
        public int emisionevento_numero { get; set; }
        public int emisionevento_usuario_id { get; set; }
        public Nullable<System.DateTime> emisionevento_fecha_fin { get; set; }
    
        public virtual eventoestado eventoestado { get; set; }
        public virtual emisionlimite emisionlimite { get; set; }
        public virtual poliza poliza { get; set; }
    }
}
