//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfilaplicacion
    {
        public int perfilaplicacion_id { get; set; }
        public int perfilaplicacion_perfil_id { get; set; }
        public int perfilaplicacion_aplicacion_id { get; set; }
    
        public virtual aplicacion aplicacion { get; set; }
        public virtual perfil perfil { get; set; }
    }
}
