//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class polizaestado
    {
        public polizaestado()
        {
            this.poliza = new HashSet<poliza>();
        }
    
        public int polizaestado_id { get; set; }
        public string polizaestado_estado { get; set; }
        public string polizaestado_descripcion { get; set; }
    
        public virtual ICollection<poliza> poliza { get; set; }
    }
}
