//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilegio
    {
        public privilegio()
        {
            this.perfilprivilegio = new HashSet<perfilprivilegio>();
        }
    
        public int privilegio_id { get; set; }
        public string privilegio_nombre { get; set; }
        public string privilegio_descripcion { get; set; }
    
        public virtual ICollection<perfilprivilegio> perfilprivilegio { get; set; }
    }
}
