//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramo
    {
        public ramo()
        {
            this.emisionlimite = new HashSet<emisionlimite>();
        }
    
        public int ramo_producto_1 { get; set; }
        public int ramo_producto_2 { get; set; }
        public string ramo_nombre { get; set; }
    
        public virtual ICollection<emisionlimite> emisionlimite { get; set; }
    }
}
