//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.customer = new HashSet<customer>();
            this.inventory = new HashSet<inventory>();
            this.staff = new HashSet<staff>();
        }
    
        public byte store_id { get; set; }
        public byte manager_staff_id { get; set; }
        public int address_id { get; set; }
        public System.DateTime last_update { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<customer> customer { get; set; }
        public virtual ICollection<inventory> inventory { get; set; }
        public virtual ICollection<staff> staff { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
