//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegConRep
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usuario_id { get; set; }
        public string usuario_usuario { get; set; }
        public string usuario_email { get; set; }
        public Nullable<int> usuario_grupo_id { get; set; }
        public Nullable<int> usuario_perfil_id { get; set; }
        public Nullable<int> usuario_estadousuario_id { get; set; }
        public string usuario_clave { get; set; }
        public string usuario_nombre { get; set; }
    
        public virtual estadousuario estadousuario { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual perfil perfil { get; set; }
    }
}
